<a href="https://colab.research.google.com/github/mpanime21-create/Week3_Lab_ML_course/blob/main/exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Fundamentals Exercises

This notebook contains exercises based on the PyTorch Fundamentals tutorial. Each section corresponds to a topic from the original notebook. Complete the exercises by filling in the code cells where indicated.

## 1. Introduction to Tensors

### Exercise 1.1: Create a scalar tensor
Create a scalar tensor with the value 42 and print its value, number of dimensions (ndim), and shape.

In [3]:
import torch

# TODO: Create a scalar tensor
scalar = torch.tensor([7,14,99])

# Print details
print(scalar)
print(f"Number of dimensions: {scalar.ndim}")
print(f"Shape: {scalar.shape}")

tensor([ 7, 14, 99])
Number of dimensions: 1
Shape: torch.Size([3])


### Exercise 1.2: Create a vector tensor
Create a vector tensor with values [1, 2, 3, 4] and print its value, ndim, and shape.

In [6]:
# TODO: Create a vector tensor
vector = torch.tensor([3,4])

# Print details
print(vector)
print(f"Number of dimensions: {vector.ndim}")
print(f"Shape: {vector.shape}")

tensor([3, 4])
Number of dimensions: 1
Shape: torch.Size([2])


### Exercise 1.3: Create a matrix tensor
Create a 2x3 matrix tensor with values [[1, 2, 3], [4, 5, 6]] and print its details.

In [9]:
# TODO: Create a matrix tensor
matrix = torch.tensor([[5,7,3],
                       [8,9,4]])

# Print details
print(matrix)
print(f"Number of dimensions: {matrix.ndim}")
print(f"Shape: {matrix.shape}")

tensor([[5, 7, 3],
        [8, 9, 4]])
Number of dimensions: 2
Shape: torch.Size([2, 3])


### Exercise 1.4: Create a 3D tensor
Create a tensor of shape (2, 2, 2) with sequential values from 1 to 8 using torch.arange and reshape.

In [13]:
# TODO: Create a 3D tensor
tensor_3d = torch.tensor([[[1,2,3],
                          [3,4,5],
                          [5,6,7]]])

# Print details
print(tensor_3d)
print(f"Number of dimensions: {tensor_3d.ndim}")
print(f"Shape: {tensor_3d.shape}")

tensor([[[1, 2, 3],
         [3, 4, 5],
         [5, 6, 7]]])
Number of dimensions: 3
Shape: torch.Size([1, 3, 3])


## 2. Random Tensors

### Exercise 2.1: Create a random tensor
Create a random tensor of shape (4, 4) and print it along with its dtype.

In [20]:
# TODO: Create random tensor
random_tensor = torch.rand(size=(3,3))

print(random_tensor)
print(f"Datatype: {random_tensor.dtype}")

tensor([[0.7711, 0.3352, 0.8789],
        [0.8611, 0.8019, 0.8404],
        [0.6643, 0.6454, 0.5131]])
Datatype: torch.float32


### Exercise 2.2: Create an image-sized random tensor
Create a random tensor of shape (3, 224, 224) simulating an image (channels, height, width).

In [22]:
# TODO: Create image-sized random tensor
image_tensor = torch.rand(size = (256,134,236))

print(f"Shape: {image_tensor.shape}")

Shape: torch.Size([256, 134, 236])


## 3. Zeros and Ones

### Exercise 3.1: Create a tensor of zeros
Create a tensor of zeros with shape (5, 5).

In [26]:
# TODO: Create zeros tensor
zeros = torch.zeros(size = (3,3))
zeros, zeros.dtype

(tensor([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]),
 torch.float32)

### Exercise 3.2: Create a tensor of ones like another tensor
Create a random tensor of shape (3, 3), then create a tensor of ones with the same shape using ones_like.

In [56]:
random_tensor = torch.rand(3, 3)
# TODO: Create ones like
ones_like = torch.ones_like(input = random_tensor)

print(random_tensor)
print(ones_like)

tensor([[0.9963, 0.6396, 0.3026],
        [0.3406, 0.9424, 0.1716],
        [0.6942, 0.5744, 0.5444]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


## 4. Creating Ranges

### Exercise 4.1: Create a range tensor
Create a tensor with values from 0 to 20 with a step of 2 using torch.arange.

In [60]:
# TODO: Create range tensor
range_tensor = torch.arange(0,21,1)

range_tensor

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20])

## 5. Tensor Datatypes

### Exercise 5.1: Create tensors with specific dtypes
Create a tensor with values [1.0, 2.0, 3.0] using dtype=torch.float16 and another with dtype=torch.int64.

In [67]:
# TODO: float16 tensor
float16_tensor = torch.tensor([3.14,2.71],
                              dtype = torch.float16)
print(float16_tensor)
# TODO: int64 tensor
int64_tensor = torch.tensor([3.14,2.71],
                              dtype = torch.float64)
print(int64_tensor)

tensor([3.1406, 2.7109], dtype=torch.float16)
tensor([3.1415, 2.7100], dtype=torch.float64)


### Exercise 5.2: Change dtype
Convert the float16_tensor to float32.

In [69]:
# TODO: Change dtype
float32_tensor = float16_tensor.to(torch.float32)

print(float32_tensor, )

tensor([3.1406, 2.7109])


## 6. Getting Information from Tensors

### Exercise 6.1: Print tensor info
Create a random tensor of shape (2, 3, 4) and print its shape, dtype, and device.

In [70]:
# TODO: Create tensor and print info
info_tensor = torch.rand(2,3,4)

print(info_tensor)
print(f"Shape of tensor: {info_tensor.shape}")
print(f"Data type of tensor: {info_tensor.dtype}")
print(f"Device tensor is stored on: {info_tensor.device}")

tensor([[[0.4959, 0.7180, 0.1884, 0.0091],
         [0.9966, 0.9575, 0.1693, 0.2817],
         [0.9619, 0.8460, 0.3094, 0.5306]],

        [[0.2849, 0.9278, 0.5070, 0.9010],
         [0.8641, 0.2425, 0.9335, 0.7387],
         [0.3858, 0.7012, 0.5355, 0.7556]]])
Shape of tensor: torch.Size([2, 3, 4])
Data type of tensor: torch.float32
Device tensor is stored on: cpu


## 7. Manipulating Tensors (Basic Operations)

### Exercise 7.1: Perform basic operations
Create a tensor [10, 20, 30]. Add 5, subtract 10, multiply by 2, and divide by 10.

In [100]:
tensor = torch.tensor([10, 20, 30])
# TODO: Add 5
print(tensor + 5)

# TODO: Subtract 10
print(tensor - 10)

# TODO: Multiply by 2
print(tensor * 2)

# TODO: Divide by 10
print(tensor / 10)

tensor([15, 25, 35])
tensor([ 0, 10, 20])
tensor([20, 40, 60])
tensor([1., 2., 3.])


### Exercise 7.2: Matrix multiplication
Create two tensors A (2x3) and B (3x2) with random values and perform matrix multiplication.

In [102]:
# TODO: Create A and B
A = torch.rand(2,3)
B = torch.rand(3,2)

# TODO: Matrix mul using torch.mm
result_mm = torch.matmul(A, B)
print("torch.matmul result:\n", result_mm)

# TODO: Matrix mul using @
result_at = A @ B
print("@ operator result:\n", result_at)

torch.matmul result:
 tensor([[1.1706, 1.2730],
        [0.6365, 0.8520]])
@ operator result:
 tensor([[1.1706, 1.2730],
        [0.6365, 0.8520]])


## 8. Tensor Aggregation

### Exercise 8.1: Find min, max, mean, sum
Create a tensor with values from 0 to 100 and find its min, max, mean, and sum.

In [104]:
agg_tensor = torch.arange(0, 101)
# TODO: Min
min_val = torch.min(agg_tensor)
print("Min: ", min_val.item())

# TODO: Max
max_val = torch.max(agg_tensor)
print("Max: ", max_val.item())

# TODO: Mean (note: may need to cast to float)
mean_val = torch.mean(agg_tensor.float())
print("Mean:", mean_val.item())

# TODO: Sum
sum_val = torch.sum(agg_tensor)
print("Sum: :", sum_val.item())

Min:  0
Max:  100
Mean: 50.0
Sum: : 5050


### Exercise 8.2: Argmin and argmax
Find the positions of the minimum and maximum values in the above tensor.

In [105]:
# TODO: Argmin
min_pos = torch.argmin(agg_tensor)
print("Position of min:", min_pos.item())

# TODO: Argmax
max_pos = torch.argmax(agg_tensor)
print("Position of max:", max_pos.item())

Position of min: 0
Position of max: 100


## 9. Reshaping, Stacking, Squeezing, Unsqueezing

### Exercise 9.1: Reshape a tensor
Create a tensor of shape (10,) and reshape it to (2, 5).

In [107]:
reshape_tensor = torch.arange(10)
# TODO: Reshape
reshaped = reshape_tensor.reshape(2,5)
print("Reshaped tensor:", reshaped)

Reshaped tensor: tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


### Exercise 9.2: Stack tensors
Create two tensors of shape (2, 2) and stack them vertically and horizontally.

In [111]:
tensor1 = torch.rand(2, 2)
tensor2 = torch.rand(2, 2)

# TODO: Stack vertically (dim=0)
vertical_stack = torch.cat((tensor1,tensor2), dim=0)
print("Vertical stack (dim=0):", vertical_stack)

# TODO: Stack horizontally (dim=1)
horizontal_stack = torch.cat((tensor1,tensor2), dim=1)
print("Horizontal stack (dim=0):", horizontal_stack )

Vertical stack (dim=0): tensor([[0.4614, 0.5945],
        [0.4297, 0.2690],
        [0.4546, 0.7448],
        [0.8710, 0.3832]])
Horizontal stack (dim=0): tensor([[0.4614, 0.5945, 0.4546, 0.7448],
        [0.4297, 0.2690, 0.8710, 0.3832]])


### Exercise 9.3: Squeeze and unsqueeze
Create a tensor of shape (1, 3, 1), squeeze it, then unsqueeze it back on dim=0.

In [113]:
squeeze_tensor = torch.rand(1, 3, 1)
# TODO: Squeeze
squeezed = torch.squeeze(squeeze_tensor)
print("Squeezed tensor:\n", squeezed)
print("Shape:", squeezed.shape)

# TODO: Unsqueeze on dim=0
unsqueezed = torch.unsqueeze(squeeze_tensor, dim=0)
print("Unsqueezed tensor (dim=0):\n", unsqueezed)
print("Shape:", unsqueezed.shape)

Squeezed tensor:
 tensor([0.7335, 0.1492, 0.4962])
Shape: torch.Size([3])
Unsqueezed tensor (dim=0):
 tensor([[[[0.7335],
          [0.1492],
          [0.4962]]]])
Shape: torch.Size([1, 1, 3, 1])


### Exercise 9.4: Permute
Create an image tensor (3, 100, 100) and permute it to (100, 100, 3).

In [114]:
image_tensor = torch.rand(3, 100, 100)
# TODO: Permute
permuted = image_tensor.permute(1,2,0)
print("Permuted tensor shape:", permuted.shape)

Permuted tensor shape: torch.Size([100, 100, 3])


## 10. Indexing

### Exercise 10.1: Index into a tensor
Create a tensor [[[1,2,3],[4,5,6],[7,8,9]]] and index to get 5, then the entire second row.

In [115]:
index_tensor = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
# TODO: Get 5
value_5 = index_tensor[0, 1, 1]
print("Value 5:", value_5.item())

# TODO: Get second row [4,5,6]
second_row = index_tensor[0, 1, :]
print("Second row:", second_row)

Value 5: 5
Second row: tensor([4, 5, 6])


## 11. PyTorch and NumPy

### Exercise 11.1: NumPy to PyTorch
Create a NumPy array [1,2,3,4] and convert it to a PyTorch tensor.

In [116]:
import numpy as np
numpy_array = np.array([1,2,3,4])

# TODO: Convert to tensor
from_numpy = torch.from_numpy(numpy_array)
print("Tensor from NumPy array:", from_numpy)
print("Type:", type(from_numpy))

Tensor from NumPy array: tensor([1, 2, 3, 4])
Type: <class 'torch.Tensor'>


### Exercise 11.2: PyTorch to NumPy
Create a PyTorch tensor [5,6,7,8] and convert it to a NumPy array.

In [117]:
pytorch_tensor = torch.tensor([5,6,7,8])
# TODO: Convert to NumPy
to_numpy = pytorch_tensor.numpy()
print("NumPy array:", to_numpy)
print("Type:", type(to_numpy))

NumPy array: [5 6 7 8]
Type: <class 'numpy.ndarray'>


## 12. Reproducibility

### Exercise 12.1: Set manual seed
Set the manual seed to 77 and create two random tensors of shape (2,2). Check if they are equal.

In [118]:
# TODO: Set seed
torch.manual_seed(77)
rand1 = torch.rand(2,2)

# TODO: Reset seed for second tensor
torch.manual_seed(77)
rand2 = torch.rand(2,2)

# Check equality
print(rand1 == rand2)

tensor([[True, True],
        [True, True]])


## 13. Running on GPUs

### Exercise 13.1: Check for GPU
Write code to check if CUDA is available and set the device accordingly.

In [121]:
# TODO: Set device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

tensor_on_device = torch.rand(2, 2, device=device)
print("Tensor on device:\n", tensor_on_device)
print("Tensor device:", tensor_on_device.device)

Device: cpu
Tensor on device:
 tensor([[0.3538, 0.3347],
        [0.7285, 0.5794]])
Tensor device: cpu


### Exercise 13.2: Move tensor to GPU
Create a tensor and move it to the GPU if available. Then move it back to CPU and convert to NumPy.

In [122]:
gpu_tensor = torch.tensor([10, 20, 30])
# TODO: Move to device
gpu_tensor = gpu_tensor.to(device)
print("Tensor on device:", gpu_tensor)
print("Device:", gpu_tensor.device)

# TODO: Move back to CPU and to NumPy
cpu_numpy = gpu_tensor.cpu().numpy()
print("Tensor on CPU as NumPy array:", cpu_numpy)
print("Type:", type(cpu_numpy))

Tensor on device: tensor([10, 20, 30])
Device: cpu
Tensor on CPU as NumPy array: [10 20 30]
Type: <class 'numpy.ndarray'>
